// <auto-generated />
namespace BooksCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_constraints_to_category_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_constraints_to_category_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201610201751023_add_constraints_to_category_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
