// <auto-generated />
namespace BooksCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class make_book_name_field_larger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_book_name_field_larger));
        
        string IMigrationMetadata.Id
        {
            get { return "201610192217287_make_book_name_field_larger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
